### ISSUE TITLE
cann t run

### ISSUE THREAD

**Issue by Dyf-hue** [JianghaiSCU/RFLLIE#1]
If you don't want to share your code for others to use, you can simply say so, instead of creating a rudimentary readme and providing code that can hardly be executed, wasting others' time.

**Comment by JianghaiSCU** [comment]
If you don't have the ability to modify the code to adapt it to your environment, then what you need is to improve your coding skills instead of commenting here, which is what you must have when trying to reproduce most of the existing open-source methods.

**Comment by Dyf-hue** [comment]
I apologize for my previous rashness. Many packages in the requirement.txt could not be downloaded directly, and because of using distributed training, the test code also needed modification, which took me some time. I got a bit excited, but regardless, it was my own fault. I apologize to you again.

**Comment by JianghaiSCU** [comment]
You can delete packages that cannot be downloaded without affecting your subsequent training and testing, as some may only be suitable for my environment. During the testing phase, you should use 1 GPU as we declared in https://github.com/JianghaiSCU/RFLLIE/blob/018204291b702b7975a240cf9601f5372df953b6/main.py#L46.
